addSbtPlugin("com.github.sbt"            % "sbt-eclipse"  % "6.0.0")
addSbtPlugin("com.github.sbt"            % "sbt-git"      % "2.0.1")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"      % "2.3.1")
addSbtPlugin("io.gatling"                % "gatling-sbt"  % "3.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.0")
